# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc6fc5d342b8c5c8926d1cbe74e11e2b00c3e417534e6636e63cd7b060b13906c6b4e1419f601752f008f47fe3a4c1b56a799daa02a4450773cf94972a3faf0

test:
  secret_key_base: 0f91020263c98c4684c54dcf694d384c0689d02a6450fcc13fa27a1d9b0fc35d9e4a4b8417ad43118c99de3a5b90630e00d9e2a2aad997bac9d3bb6fabbc00e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
